services:
  odoo:
    image: odoo:17
    ports:
      - "8069:8069"
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-data:/var/lib/odoo

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - db-data:/var/lib/postgresql/data

  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    volumes:
      - ~/.ngrok2:/var/lib/ngrok
    command: http odoo:8069 --log=stdout
    depends_on:
      - odoo

volumes:
  odoo-data:
  db-data:
